name: Auto Review Assignment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewers dynamically
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            let reviewers = [];

            if (pr.assignees.length > 0) {
              reviewers = pr.assignees.map(a => a.login);
            } else {
              reviewers = ["LEI-129334", "LEI-62015", "LEI-99917", "LEI105514"];
            }

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers: reviewers
            });
